### ISSUE TITLE
为什么用代码返回没有买的交易对数据？

### ISSUE THREAD

**Issue by charmi12** [chainx-org/chainx-wallet-bug-bounty#20]
输入chainx.trade.getQuotations（0,2）返回的数据没有买单的数据
![无标题](https://user-images.githubusercontent.com/38544263/76398460-e2980500-63b7-11ea-94a2-389dd31d6202.jpg)

**Comment by liuchengxu** [comment]
`buy` 字段就是买单数据，只不过此时取得的值是空 [].

**Comment by charmi12** [comment]
> `buy` 字段就是买单数据，只不过此时取得的值是空 [].

为什么取值为空，明明有买单挂着？

**Comment by liuchengxu** [comment]
RPC的报价接口出于性能考虑并不返回当前的所有报价信息，只返回盘口附近的部分报价，不返回距离盘口太远的报价。

**Comment by charmi12** [comment]
> RPC的报价接口出于性能考虑并不返回当前的所有报价信息，只返回盘口附近的部分报价，不返回距离盘口太远的报价。

这样有点不合理，dex没有深度，盘口价格很容易人为控制，那就导致无法正常读取挂单数据。除非盘口的价格是跟踪市场化的价格。
