### ISSUE TITLE
节点赎回投票，显示的赎回锁定期为3天，实际为30天

### ISSUE THREAD

**Issue by caoyu1988** [chainx-org/chainx-wallet-bug-bounty#21]
![image](https://user-images.githubusercontent.com/7642808/77150195-4c0dc700-6ace-11ea-9cc3-c3fe98796194.png)

**Comment by wliyongfeng** [comment]
@caoyu1988 好的，感谢，请留下PCX地址，给你一定的奖励。

**Comment by caoyu1988** [comment]
5TSdBip3rwGjAz9NA1Z1TZR8yoX6Q12gK3pY7GMyqDutGrUF    感谢

**Comment by notvalley** [comment]
已打：https://scan.chainx.org/txs/0xade650631cb04a0aa8e0e9c74026648eecd1cb3c18c11cffd236bac5882fc788

**Comment by wliyongfeng** [comment]
@caoyu1988 已经修复，麻烦验证下看还有没有问题。

**Comment by caoyu1988** [comment]
已修复，谢谢
