### ISSUE TITLE
[chainX 2.0] dapp页power图不对

### ISSUE THREAD

**Issue by ww8912188** [chainx-org/chainx-wallet-bug-bounty#44]
重现步骤:
1. 打开https://dapp-v2.chainx.org/
2. 右下角的power图并不是当前账户的资产分布图

查了下接口似乎未返回正确的值。

参考下面图片:
[image.png](https://upload-images.jianshu.io/upload_images/9638496-b4a7476e29ff69fa.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by aaurix** [comment]
图片无法打开
