### ISSUE TITLE
Issue going to motions page through council page on dapp-v2

### ISSUE THREAD

**Issue by Exxibition** [chainx-org/chainx-wallet-bug-bounty#57]
Describe the bug: When going to governance > council, then 'motions' the page errors with the following: ```Uncaught error. Something went wrong with the query and rendering of this component. (0 , o.useAvailableSlashes) is not a function```

To Reproduce: navigate to governance > council > motions on https://dapp-v2.chainx.org/

Expected behavior: Probably see the motions put forward to vote on i presume. 

Log if applicable, attach the console output here.

Screenshots If applicable, add screenshots to help explain your problem.

Account Info UserOrNode: Not relevant, but both Node and User. 
ChainX Wallet Address(Major Chain): 5TLM4wEBMEJysMSj5TY5BKv3K4aaE1XRE5mv6FUt6NzT1PFT

**Comment by aaurix** [comment]
fixed
