### ISSUE TITLE
区块浏览器各奖池金额与实际金额不符

### ISSUE THREAD

**Issue by feilun-feilun** [chainx-org/chainx-wallet-bug-bounty#61]
**Describe the bug**
在区块浏览器里任意点一个节点，其在节点列表里的奖池余额与点进对应奖池后的金额不符，且经观察，列表金额有误。
钱包显示的奖池金额与对应奖池地址金额一致。
**Screenshots**
![屏幕快照 2020-11-06 下午9 08 09](https://user-images.githubusercontent.com/49551621/98369804-7ff52700-2074-11eb-956a-d1b7f55c5cd5.png)
![屏幕快照 2020-11-06 下午9 07 51](https://user-images.githubusercontent.com/49551621/98369813-82578100-2074-11eb-97fa-b0269606fd05.png)

**Account Info**
Node: Feilun
ChainX Wallet Address(Major Chain):
5U2Cty9khm9aW762o14GUHHBcLU1PbqRuRomW33EbQpUAHxS

**Comment by tarvos21** [comment]
Already fixed it. Please close the issue. @liuchengxu
