### ISSUE TITLE
2.0 钱包XBTC无法转账

### ISSUE THREAD

**Issue by feilun-feilun** [chainx-org/chainx-wallet-bug-bounty#63]
**Describe the bug**
在账户中，点击“发送”，目前只能选择转账pcx的单位，而无法选择币种；
在跨链资产中，目前还看不到界面，所以不确定在哪里能对XBTC进行转账。

**Screenshots**
![屏幕快照 2020-11-09 上午10 56 27](https://user-images.githubusercontent.com/49551621/98495970-5fe38480-227b-11eb-8700-1c9076187028.png)

Account Info
Node: Feilun
ChainX Wallet Address(Major Chain):
5U2Cty9khm9aW762o14GUHHBcLU1PbqRuRomW33EbQpUAHxS

**Comment by aaurix** [comment]
fixed
