### ISSUE TITLE
投票界面提息报错

### ISSUE THREAD

**Issue by wenzhenxiang** [chainx-org/chainx-wallet-bug-bounty#8]
从节点投票提息时，显示提交交易出错，插件存在尚未处理的签名请求，如图 
持续5-10分钟仍是这种情况，不知道和延时是不是同一问题，改用PC端节点投票提息正常

![image](https://user-images.githubusercontent.com/18651846/76064989-b0586300-5fc5-11ea-897f-916ffaa43452.png)

**Comment by wliyongfeng** [comment]
这个是正常的，需要先打开插件，然后把待签的交易取消掉。

**Comment by wenzhenxiang** [comment]
对，是我弄错了
